### PR TITLE
Revise visualisations

### PR DESCRIPTION
**Pull request by ekatef**
PR aims to make visualisations more clear for a modeller. Main changes introduced:
1. added a generation and load parameters for the spatial plot (partially addresses #9);
2. generators to be shown by color filling are filtered to be renewable only (partially addresses #9);
3. revised layout for System Operation: only `Suppy` and `Demand` plot are left at the moment to keep the focus;
4. revised labels and content of `Suppy` and `Demand` plots (partially addresses #10)

### CODE REVIEW

**Comment by ekatef** [comment]
Hello @drifter089! Have revised visualisations a bit.

The idea is to make plots correct and as nice and clear as we can, as the first step. Once we'll be happy with the results, the commented-out plots and selections can be get back.

Feel free to disagree and comment on the suggested changes :)

**Comment by ekatef** [comment]
@drifter089 @pz-max I believe that is ready for review 🙂

**Comment by pz-max** [comment]
Feel free to merge after review from @drifter089

**Comment by pz-max** [comment]
Reviewed and merged. Just found this issue here that there is two times `p_nom` (nominal power with somewhat different results being plotted)
image

**Comment by ekatef** [comment]
> Reviewed and merged. Just found this issue here that there is two times `p_nom` (nominal power with somewhat different results being plotted)

Thanks for review @pz-max! There are currently both `p_nom` and `p_nom_opt`, although agree that `p_nom` is not very meaningful and can be misleading. Fixing it.

**Pull request merged**
